/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "HandyPTG_constants.h"



const HandyPTGConstants g_HandyPTG_constants;

HandyPTGConstants::HandyPTGConstants() {
}



